services:
  - type: web
    name: bulkflow-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bulkflow-db
          property: connectionString
      - key: REDIS_URL
        value: redis://default:DUVIfYw3qdh5arET4rfrVHpcozRtR6Sv@redis-10475.c273.us-east-1-2.ec2.cloud.redislabs.com:10475

  - type: pserv
    name: bulkflow-celery
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config worker --loglevel=info --pool=gevent"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bulkflow-db
          property: connectionString
      - key: REDIS_URL
        value: redis://default:DUVIfYw3qdh5arET4rfrVHpcozRtR6Sv@redis-10475.c273.us-east-1-2.ec2.cloud.redislabs.com:10475

databases:
  - name: bulkflow-db
    databaseName: product_importer
    user: bulkflow